### ISSUE TITLE
help set server

### ISSUE THREAD

**Issue by smartekIT** [Electronprod/Java-RAT-Server#1]
Hi,
how to set the address for the main server in the client app? any detailed document on how to install and use client/server RAT is much appreciated.
Thanks

**Comment by Electronprod** [comment]
> Hi, how to set the address for the main server in the client app? any detailed document on how to install and use client/server RAT is much appreciated. Thanks

Hello. Installation guide for server added to README. Java-RAT client requires only installed Java 8+. You download the file and run it. The server address can be specified in Java-Rat in the host.txt file in the same directory (you can create it) or inside the .jar file. (default address set inside .jar is: localhost:50000) Here is the file format: https://github.com/Electronprod/Java-RAT/blob/master/src/electron/host.txt

**Comment by smartekIT** [comment]
Thanks heaps, I will give it a go.
