### ISSUE TITLE
what recommended IDE to build this

### ISSUE THREAD

**Issue by smartekIT** [Electronprod/Java-RAT-Server#2]
sorry if this sounds a stupid question, but what IDE we should be importing this project and the other RAT into to build?
eclipse or electron forge or netbeans .. etc

Thanks

**Comment by Electronprod** [comment]
> sorry if this sounds a stupid question, but what IDE we should be importing this project and the other RAT into to build?
> 
> eclipse or electron forge or netbeans .. etc
> 
> 
> 
> Thanks

Hello. These projects are developed in Eclipse IDE.

**Comment by smartekIT** [comment]
Thanks
